c_stdlib_version:   # [osx and x86_64]
  - 10.15           # [osx and x86_64]


# Follow https://github.com/conda-forge/pytorch-cpu-feedstock/blob/main/recipe/conda_build_config.yaml
# And https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6643
# https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/6630
# Needs higher stdlib for CUDNN9
# CUDA 12 on aarch needs newer glibc, which requires us to override
# the whole monster zip just to bump c_stdlib_version / docker_image
# We have dropped 11.8 due to lack of interest from conda-forge pytorch maintainers
c_stdlib_version:                                   # [linux and aarch64]
  - 2.17                                            # [linux and aarch64]
  - 2.28                                            # [linux and aarch64]
docker_image:                                       # [linux and aarch64]
  - quay.io/condaforge/linux-anvil-x86_64:cos7      # [linux and aarch64]
  - quay.io/condaforge/linux-anvil-x86_64:alma9     # [linux and aarch64]
# rest just to make smithy happy
c_compiler_version:                                 # [linux and aarch64]
  - 13                                              # [linux and aarch64]
  - 12                                              # [linux and aarch64]
cxx_compiler_version:                               # [linux and aarch64]
  - 13                                              # [linux and aarch64]
  - 12                                              # [linux and aarch64]
fortran_compiler_version:                           # [linux and aarch64]
  - 13                                              # [linux and aarch64]
  - 12                                              # [linux and aarch64]
cuda_compiler:                                      # [linux and aarch64]
  - None                                            # [linux and aarch64]
  - cuda-nvcc                                       # [linux and aarch64]
cuda_compiler_version:                              # [linux and aarch64]
  - None                                            # [linux and aarch64]
  - 12.6                                            # [linux and aarch64]
# end override of monster zip
